import type { Course } from '@/types/course.types'
import { authAPI, USE_MOCK } from './api'

const MOCK_COURSES: Course[] = [
  {
    id: 'cr1',
    name: 'Pengenalan Huruf',
    level: 'Level : 2 (Dua)',
    progress: 80,
    completedSessions: 3,
    totalSessions: 4,
    tanggalMulai: '2026-05-20',
    status: 'dipelajari',
    exercises: [
      {
        id: 'a',
        title: 'Membaca',
        progress: 75,
        completedSessions: 3,
        totalSessions: 4,
        isCompleted: false,
      },
      {
        id: 'a',
        title: 'Membaca',
        progress: 75,
        completedSessions: 3,
        totalSessions: 4,
        isCompleted: false,
      },
      {
        id: 'a',
        title: 'Membaca',
        progress: 75,
        completedSessions: 3,
        totalSessions: 4,
        isCompleted: false,
      },
      {
        id: 'a',
        title: 'Membaca',
        progress: 75,
        completedSessions: 3,
        totalSessions: 4,
        isCompleted: false,
      },
      {
        id: 'a',
        title: 'Membaca',
        progress: 75,
        completedSessions: 3,
        totalSessions: 4,
        isCompleted: false,
      },
      {
        id: 'a',
        title: 'Membaca',
        progress: 75,
        completedSessions: 3,
        totalSessions: 4,
        isCompleted: false,
      },
    ],
  },
  {
    id: 'cr2',
    name: 'Pengenalan Huruf',
    level: 'Level : 3 (Tiga)',
    progress: 0,
    completedSessions: 0,
    totalSessions: 5,
    tanggalMulai: '2026-05-20',
    status: 'belum',
    exercises: [
      {
        id: 'a',
        title: 'Membaca',
        progress: 75,
        completedSessions: 3,
        totalSessions: 4,
        isCompleted: false,
      },
      {
        id: 'a',
        title: 'Membaca',
        progress: 75,
        completedSessions: 3,
        totalSessions: 4,
        isCompleted: false,
      },
      {
        id: 'a',
        title: 'Membaca',
        progress: 75,
        completedSessions: 3,
        totalSessions: 4,
        isCompleted: false,
      },
      {
        id: 'a',
        title: 'Membaca',
        progress: 75,
        completedSessions: 3,
        totalSessions: 4,
        isCompleted: false,
      },
      {
        id: 'a',
        title: 'Membaca',
        progress: 75,
        completedSessions: 3,
        totalSessions: 4,
        isCompleted: false,
      },
      {
        id: 'a',
        title: 'Membaca',
        progress: 75,
        completedSessions: 3,
        totalSessions: 4,
        isCompleted: false,
      },
    ],
  },

  {
    id: 'cr3',
    name: 'Pengenalan Huruf',
    level: 'Level : 1 (Satu)',
    progress: 100,
    completedSessions: 4,
    totalSessions: 4,
    tanggalMulai: '2026-05-20',
    status: 'selesai',
    exercises: [
      {
        id: 'a',
        title: 'Membaca',
        progress: 75,
        completedSessions: 3,
        totalSessions: 4,
        isCompleted: false,
      },
      {
        id: 'a',
        title: 'Membaca',
        progress: 75,
        completedSessions: 3,
        totalSessions: 4,
        isCompleted: false,
      },
      {
        id: 'a',
        title: 'Membaca',
        progress: 75,
        completedSessions: 3,
        totalSessions: 4,
        isCompleted: false,
      },
      {
        id: 'a',
        title: 'Membaca',
        progress: 75,
        completedSessions: 3,
        totalSessions: 4,
        isCompleted: false,
      },
      {
        id: 'a',
        title: 'Membaca',
        progress: 75,
        completedSessions: 3,
        totalSessions: 4,
        isCompleted: false,
      },
      {
        id: 'a',
        title: 'Membaca',
        progress: 75,
        completedSessions: 3,
        totalSessions: 4,
        isCompleted: false,
      },
    ],
  },
  {
    id: 'cr4',
    name: 'Pengenalan Huruf',
    level: 'Level : 3 (Tiga)',
    progress: 0,
    completedSessions: 0,
    totalSessions: 5,
    tanggalMulai: '2026-05-20',
    status: 'belum',
  },
  {
    id: 'cr3',
    name: 'Pengenalan Huruf',
    level: 'Level : 1 (Satu)',
    progress: 100,
    completedSessions: 4,
    totalSessions: 4,
    tanggalMulai: '2026-05-20',
    status: 'selesai',
  },
  {
    id: 'cr4',
    name: 'Pengenalan Huruf',
    level: 'Level : 3 (Tiga)',
    progress: 0,
    completedSessions: 0,
    totalSessions: 5,
    tanggalMulai: '2026-05-20',
    status: 'belum',
    exercises: [
      {
        id: 'a',
        title: 'Membaca',
        progress: 75,
        completedSessions: 3,
        totalSessions: 4,
        isCompleted: false,
      },
      {
        id: 'a',
        title: 'Membaca',
        progress: 75,
        completedSessions: 3,
        totalSessions: 4,
        isCompleted: false,
      },
      {
        id: 'a',
        title: 'Membaca',
        progress: 75,
        completedSessions: 3,
        totalSessions: 4,
        isCompleted: false,
      },
      {
        id: 'a',
        title: 'Membaca',
        progress: 75,
        completedSessions: 3,
        totalSessions: 4,
        isCompleted: false,
      },
      {
        id: 'a',
        title: 'Membaca',
        progress: 75,
        completedSessions: 3,
        totalSessions: 4,
        isCompleted: false,
      },
      {
        id: 'a',
        title: 'Membaca',
        progress: 75,
        completedSessions: 3,
        totalSessions: 4,
        isCompleted: false,
      },
    ],
  },
  { id: 'cr8', name: 'Course A', progress: 20, completedSessions: 2, totalSessions: 10 },
  { id: 'cr9', name: 'Course A', progress: 20, completedSessions: 2, totalSessions: 10 },
  { id: 'cr10', name: 'Course 10', progress: 20, completedSessions: 2, totalSessions: 10 },
]
export const courseService = {
  async getCourses(childId: string): Promise<Course[]> {
    if (USE_MOCK) return MOCK_COURSES
    const res = await authAPI.get<Course[]>(`/children/${childId}/courses`)
    return res.data ?? []
  },
}
